languageCode: "en-us"
title: "ScreepsPlus"
# theme: "blackburn"
theme: ScreepsPlus

baseURL: https://screepspl.us/

canonifyurls: true
paginate: 10
enableEmoji: true
enableGitInfo: true

indexes:
  tag: "tags"
  topic: "topics"

params:
  subtitle: ""
  brand: "ScreepsPlus"
  custom_css: ["css/my.css"]
  description: "ScreepsPlus Graphs and Servers"
  # custom_js: ["js/my.js"]

menu:
  main:
  - name: "Home"
    pre: "<i class='fa fa-home fa-fw'></i>"
    weight: 1
    identifier: "home"
    url: "/"
  - name: "Forum"
    pre: "<i class='fa fa-comments fa-fw'></i>"
    weight: 80
    identifier: "forum"
    url: "https://screeps.com/forum/category/25/screepsplus"
  - name: "Wiki"
    pre: "<i class='fa fa-book fa-fw'></i>"
    weight: 90
    identifier: "wiki"
    url: "https://wiki.screepspl.us"
  - name: 'Signin'
    pre: "<i class='fa fa-user fa-fw'></i>"
    weight: 101
    identifier: "signin"
    url: "/login"


social:
  twitter: "ags131"
  github: "ScreepsPlus"
  patreon: "ags131"
  slack: "C2FD5CGJV"
